config/routes.rb
Median::Application.routes.draw do

  get "searches/create"

# Single resource

resource :session
resource :account
resource :search

resources :users
resources :categories

resources :posts do
	resource :like
	resources :user_comments, path: "comments"
	end	

root to: "posts#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :image

has_many :posts

has_attached_file :image, styles: {
	large: "500x500#",
	medium: "200x200#",
	thumbnail: "50x50#"
}

validates :title, presence: true, uniqueness: true
validates :image, attachment_presence: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id

  belongs_to :post
  belongs_to :user

  validates :body, presence: true


end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :post_id, :user_id

  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: {scope: :user_id}

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :is_featured, :title, :category_id, :image, :user_id, :tag_list, :url

  belongs_to :category
  belongs_to :user

  has_many :likes
  has_many :comments

  has_many :liked_users, through: :likes, source: :user

  scope :featured, where(is_featured: true).order("created_at desc")
  scope :not_featured, where(is_featured: false).order("created_at desc")

  has_attached_file :image, styles: {
  	large: "960x320#",
  	medium: "200x100#",
  	thumbnail: "50x50#"
  }

acts_as_taggable

acts_as_url :title

def to_param
	url
end

def self.search(query)
  where("title LIKE ? OR body LIKE ?", "%#{query}%", "%#{query}%")
end

  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :email, :name, :password_digest, :username, :avatar, :password

  has_many :posts
  has_many :likes
  has_many :comments
  has_many :liked_posts, through: :likes, source: :post

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

  has_attached_file :avatar, styles: {
  	medium: "150x150#",
  	thumbnail: "50x50#"
  }

def to_param
	username
end

def likes_post?(post)
  likes.find_by_post_id(post.id)
end

def self.search(query)
  where("username LIKE ? OR name LIKE ?", "%#{query}%", "%#{query}%")
end



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  # Make sure we're signed in
  before_filter :require_user

  def edit
  	@user = current_user
  end

  def update
  	@user = current_user

  	if @user.update_attributes(params[:user])
  		flash[:alert] = "You've updated your profile"
  	end

  	render "edit"

  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	helper_method :current_user

	def current_user
			if session[:user_id].present?
				@current_user = User.find(session[:user_id])
			else
				@current_user = nil
			end
	end


	def require_user
		if current_user.nil?
		flash[:error] = "You need to be logged in"
		redirect_to new_session_path 
		end
	end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.order(:title)
  end

  def show
  	@category = Category.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	before_filter :require_user
	before_filter :find_post

	def create
		unless current_user == @post.user
			@post.likes.create(user_id: current_user.id) 
			flash[:alert] = "You liked this post"
		else
			flash[:error] = "You can't like your own post"
		end
		
		redirect_to post_path(@post)
	end

	def destroy
		# find all the likes by that user on that post and remove them
		@post.likes.where(user_id: current_user.id).destroy_all

		flash[:alert] = "You unliked this post"

		redirect_to post_path(@post)
	end

	def find_post
		@post = Post.find_by_url(params[:post_id])
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_post, only: [:edit, :update, :destroy]

  def index

    #if there's a ?tag=something in the url
    if params[:tag].present?

      #get posts filtered by tag
      @featured  = Post.featured.tagged_with(params[:tag])
      @posts = Post.not_featured.tagged_with(params[:tag])

    else

    # otherwise get everything
    @featured = Post.featured
    @posts = Post.not_featured

    end

    # Get tags list
    @tags = Post.tag_counts.order("count desc").limit(5)

  end

  def show
    @post = Post.find_by_url(params[:id])
  end

  def new
    require_user

    # create a form for the current user adding a new post
    @post = current_user.posts.new

  end


  def create
    require_user
    @post = current_user.posts.new(params[:post])

    if @post.save
      flash[:alert] = "Yay you've added a post"
      redirect_to post_path(@post)
    else
      render "new"
    end

  end

  def edit
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:alert] = "Post Edited"
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "Post deleted"
    redirect_to root_path
  end



  def find_post
    @post = current_user.posts.find_by_url(params[:id])
    rescue
      flash[:error] = "You're not authorised to edit this"
      redirect_to root_path
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def create
  	@query = params[:search][:query]
  	@posts = Post.search(@query)
  	@users = User.search(@query)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	# try and find a user with that username
  	@user = User.find_by_username(params[:login][:username])

  	if @user.nil?
  			@user = User.find_by_email(params[:login][:username])
  	end

  	# make sure the password of that user is correct
  	@user = @user.try(:authenticate, params[:login][:password])

  	# if user and pass is correct
  	if @user

  		#set the session to that user
  		session[:user_id] = @user.id
  		flash[:alert] = "Yay you logged in"

  		redirect_to root_path

  	else
  		#show the form again
  		render "new"
  	end

  end

  def destroy
  	# delete all browser session data
  	reset_session

  	flash[:alert] = "Yay, logged out!"

  	redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find_by_username(params[:id])
  end

  def new
  		@user = User.new
  end

  def create
  		@user = User.new(params[:user])

  		if @user.save
  			# Save the user's id to our browser to mean we're logged in
  			session[:user_id] = @user.id

  			flash[:alert] = "Yay, you've signed up"
  			redirect_to root_path
  		else
  			render "new"
  		end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	# turn text in to markdown

	def md(text)
		if text.present?
			RDiscount.new(text).to_html.html_safe
		else
			""
		end

	end



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<ul>
	<% @categories.each do |cat| %>

		<li>
			<%= image_tag cat.image(:medium) if cat.image? %>

			<%= link_to cat.title, category_path(cat) %>

			<%= pluralize cat.posts.size, "post" %>
		</li>

	<% end %>

</ul>

app/views/categories/show.html.erb
<h2><%= @category.title %></h2>

<%= render partial: "posts/post", collection: @category.posts %>

app/views/posts/_actions.html.erb
	<p>
		<%= link_to "Edit", edit_post_path(@post) %>
		<%= link_to "Delete", post_path(@post), method: :delete %>
	</p>
	

app/views/posts/_comment.html.erb
<h3>Comments:</h3>

<% if @post.comments.any? %>
	<% @post.comments.each do |comment| %>
	<div class="comment">
		<h4><%= comment.user.username %> says:</h4>
		<p><%= simple_format comment.body %></p>
	</div>
	<% end %>
<% else %>
	<p>No comments</p>
<% end %>

app/views/posts/_commentsform.html.erb
<% if current_user %>
	<%= simple_form_for [@post, Comment.new], url: post_user_comments_path(@post) do |f| %>
		<%= f.input :body %>
		<%= f.button :submit %>
	<% end %>
<% else %>
	<p>You need to be logged in to comment.</p>
<% end %>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<%= f.input :title %>
	<%= f.input :body %>
	<%= f.input :image %>
	<%= f.input :category_id, as: :radio_buttons, collection: Category.order(:title) %>
	<%= f.input :tag_list %>
	<%= f.button :submit %>
<% end %>

app/views/posts/_like.html.erb
	<div class="like">

		<% if current_user == @post.user %>
			You can't like your own post
		<% elsif current_user.likes_post?(@post) %>
			<%= link_to "Unlike", post_like_path(@post), method: :delete %>
		<% else %>
			<%= link_to "Like", post_like_path(@post), method: :post %>
		<% end %>

		<p><%= pluralize @post.likes.size, "like" %></p>

		<ul>
			<% @post.liked_users.each do |user| %>
			<li>
				<%= link_to user_path(user) do %>
					<%= image_tag(user.avatar(:thumbnail))  %>
				<% end %>
			</li>	
			<% end %>

		</ul>	


	</div>

app/views/posts/_post.html.erb
<%= image_tag post.image(:medium) if post.image? %>

	<h2><%= link_to highlight(post.title, @query || ""), post_path(post) %></h2>

	<p><%= post.body %></p>

	<div class="posted_at">
			Posted at <%= post.created_at %>
	</div>

	<div class="author">
		By <%= link_to post.user.username, user_path(post.user) %>
	</div>

	<div class="category">
		<%= link_to post.category.title, 
		category_path(post.category) if post.category.present? %>
	</div>

	<div class="likes">
		<%= pluralize post.likes.size, "like" %>
	</div>

	<% if post.is_featured? %>
		<p>Featured post</p>
	<% end %>

app/views/posts/_tags.html.erb
<div class = "tags">
	<h3>Tags:</h3>
	<ul>
	<% @post.tags.each do |t| %>
		<li><%= link_to t.name, root_path(tag: t.name) %></li>
	<% end %>
	</ul>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h2>Editing "<%= @post.title %>"</h2>

<%= render partial: "form" %>

app/views/posts/index.html.erb
<h2>Featured</h2>

<%= render partial: "post", collection: @featured %>

<h2>All posts</h2>

<%= render partial: "post", collection: @posts %>

<%= render partial: "post", collection: @posts %>



<h2>All tags</h2>

<ul>
	<% @tags.each do |tag| %>

	<li>
		<%=  link_to tag.name, root_path(tag: tag.name) %>
		<strong><%= tag.count %></strong>
	</li>

	<% end %>

</ul>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render partial: "form" %>

app/views/posts/show.html.erb
<%= image_tag @post.image(:large) if @post.image? %>

<h2><%= @post.title %></h2>

<%= md @post.body %>

<div class="author">
	<%= image_tag @post.user.avatar(:medium) %>
	<%= link_to @post.user.username, user_path(@post.user) %>
</div>

<div class="posted_at">
		<%= @post.created_at %>
</div>

<%= render "tags" %>

<%= render "like" if current_user %>

<%= render "comment" %>

<%= render "commentsform" %>

<%= render "actions" if current_user == @post.user %>

app/views/users/new.html.erb
<h2>Sign up to Median</h2>

<%= simple_form_for @user do |f| %>
		<%= f.input :username %>
		<%= f.input :email, label: "Email address" %>
		<%= f.input :password %>
		<%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<p><%= @user.bio %></p>

<h3>Posts</h3>

<%= render partial: "posts/post", collection: @user.posts %>

<h3>Favourite posts:</h3>

<%= render partial: "posts/post", collection: @user.liked_posts %>